export type SymptomSeed = [slug: string, label: string, region: string];

export const SYMPTOM_SEED: SymptomSeed[] = [
  // Umum
  ["demam", "Demam", "Umum"],
  ["demam-tinggi", "Demam tinggi mendadak", "Umum"],
  ["menggigil", "Menggigil", "Umum"],
  ["kelelahan", "Kelelahan berkepanjangan", "Umum"],
  ["lemas", "Lemas / dehidrasi", "Umum"],
  ["penurunan-berat-badan", "Berat badan turun", "Umum"],
  ["kenaikan-berat-badan", "Berat badan naik", "Umum"],
  ["keringat-malam", "Keringat malam", "Umum"],
  ["keringat-dingin", "Keringat dingin", "Umum"],
  ["keringat-berlebih", "Keringat berlebih", "Umum"],
  ["pucat", "Wajah pucat", "Umum"],
  ["hilang-nafsu-makan", "Hilang nafsu makan", "Umum"],
  ["sering-haus", "Sering haus", "Umum"],
  ["intoleransi-dingin", "Tidak tahan dingin", "Umum"],
  ["ruam", "Ruam kulit", "Umum"],
  ["perdarahan-ringan", "Mimisan / gusi berdarah", "Umum"],
  ["pingsan", "Pingsan", "Umum"],
  ["kulit-kering", "Kulit kering", "Umum"],
  ["gatal", "Gatal menyeluruh", "Umum"],

  // Kepala & saraf
  ["sakit-kepala", "Sakit kepala", "Kepala & saraf"],
  ["sakit-kepala-hebat", "Sakit kepala hebat mendadak", "Kepala & saraf"],
  ["pusing", "Pusing", "Kepala & saraf"],
  ["penglihatan-kabur", "Penglihatan kabur", "Kepala & saraf"],
  ["sensitif-cahaya", "Sensitif terhadap cahaya", "Kepala & saraf"],
  ["nyeri-belakang-mata", "Nyeri di belakang mata", "Kepala & saraf"],
  ["kaku-leher", "Leher kaku", "Kepala & saraf"],
  ["kebingungan", "Kebingungan", "Kepala & saraf"],
  ["kejang", "Kejang", "Kepala & saraf"],
  ["bicara-pelo", "Bicara pelo", "Kepala & saraf"],
  ["wajah-miring", "Wajah miring sebelah", "Kepala & saraf"],
  ["kelemahan-satu-sisi", "Lemah pada satu sisi tubuh", "Kepala & saraf"],
  ["tremor", "Tremor / gemetar", "Kepala & saraf"],
  ["kaku-otot", "Otot kaku", "Kepala & saraf"],
  ["gerakan-lambat", "Gerakan melambat", "Kepala & saraf"],
  ["nyeri-rahang", "Nyeri rahang", "Kepala & saraf"],
  ["bunyi-klik-rahang", "Rahang berbunyi klik", "Kepala & saraf"],
  ["sulit-membuka-mulut", "Sulit membuka mulut", "Kepala & saraf"],

  // Dada & napas
  ["nyeri-tenggorokan", "Nyeri tenggorokan", "Dada & napas"],
  ["sulit-menelan", "Sulit menelan", "Dada & napas"],
  ["batuk", "Batuk", "Dada & napas"],
  ["batuk-kronis", "Batuk lebih dari 3 minggu", "Dada & napas"],
  ["batuk-darah", "Batuk berdarah", "Dada & napas"],
  ["dahak", "Dahak berlebih", "Dada & napas"],
  ["sesak-napas", "Sesak napas", "Dada & napas"],
  ["mengi", "Napas berbunyi mengi", "Dada & napas"],
  ["nyeri-dada", "Nyeri / tertekan di dada", "Dada & napas"],
  ["berdebar", "Jantung berdebar", "Dada & napas"],
  ["nyeri-lengan-kiri", "Nyeri menjalar ke lengan kiri", "Dada & napas"],
  ["regurgitasi", "Asam lambung naik ke mulut", "Dada & napas"],

  // Perut & pencernaan
  ["nyeri-ulu-hati", "Nyeri / perih ulu hati", "Perut & pencernaan"],
  ["mual", "Mual", "Perut & pencernaan"],
  ["muntah", "Muntah", "Perut & pencernaan"],
  ["kembung", "Perut kembung", "Perut & pencernaan"],
  ["diare", "Diare", "Perut & pencernaan"],
  ["konstipasi", "Sembelit", "Perut & pencernaan"],
  ["nyeri-perut", "Nyeri perut (difus)", "Perut & pencernaan"],
  ["nyeri-perut-kanan-atas", "Nyeri perut kanan atas", "Perut & pencernaan"],
  ["nyeri-perut-kanan-bawah", "Nyeri perut kanan bawah", "Perut & pencernaan"],
  ["nyeri-perut-kiri-bawah", "Nyeri perut kiri bawah", "Perut & pencernaan"],
  ["nyeri-perut-atas-punggung", "Nyeri perut atas menembus punggung", "Perut & pencernaan"],
  ["kulit-kuning", "Kulit / mata kuning", "Perut & pencernaan"],
  ["urine-gelap", "Urine berwarna gelap", "Perut & pencernaan"],
  ["darah-pada-tinja", "Darah pada tinja", "Perut & pencernaan"],
  ["nyeri-anus", "Nyeri / benjolan di anus", "Perut & pencernaan"],

  // Kemih
  ["nyeri-saat-berkemih", "Nyeri saat berkemih", "Saluran kemih"],
  ["sering-berkemih", "Sering berkemih", "Saluran kemih"],
  ["darah-pada-urine", "Darah pada urine", "Saluran kemih"],
  ["urine-keruh", "Urine keruh berbau", "Saluran kemih"],
  ["nyeri-pinggang", "Nyeri pinggang / sisi", "Saluran kemih"],
  ["nyeri-kolik-pinggang", "Nyeri kolik menjalar ke selangkangan", "Saluran kemih"],
  ["urine-berkurang", "Produksi urine berkurang", "Saluran kemih"],

  // Gerak & sendi
  ["nyeri-punggung-bawah", "Nyeri punggung bawah", "Gerak & sendi"],
  ["nyeri-menjalar-tungkai", "Nyeri menjalar ke tungkai", "Gerak & sendi"],
  ["kelemahan-tungkai", "Tungkai terasa lemah", "Gerak & sendi"],
  ["kesemutan", "Kesemutan / baal", "Gerak & sendi"],
  ["nyeri-sendi", "Nyeri sendi", "Gerak & sendi"],
  ["kaku-sendi", "Sendi kaku", "Gerak & sendi"],
  ["kaku-sendi-pagi", "Kaku sendi pagi > 30 menit", "Gerak & sendi"],
  ["bengkak-sendi", "Sendi bengkak", "Gerak & sendi"],
  ["kemerahan-sendi", "Sendi merah dan hangat", "Gerak & sendi"],
  ["krepitus", "Bunyi gemeretak pada sendi", "Gerak & sendi"],
  ["nyeri-otot", "Nyeri otot", "Gerak & sendi"],
  ["nyeri-betis", "Nyeri betis", "Gerak & sendi"],
  ["bengkak-kaki", "Kaki bengkak", "Gerak & sendi"],
  ["nyeri-tumit", "Nyeri tumit / belakang pergelangan", "Gerak & sendi"],
  ["nyeri-jempol-kaki", "Nyeri hebat ibu jari kaki", "Gerak & sendi"],
  ["nyeri-pergelangan-tangan", "Nyeri pergelangan tangan", "Gerak & sendi"],
  ["kelemahan-genggaman", "Genggaman melemah", "Gerak & sendi"],
  ["penurunan-tinggi-badan", "Tinggi badan menyusut", "Gerak & sendi"],
  ["patah-tulang", "Patah tulang ringan", "Gerak & sendi"],
  ["tulang-belakang-melengkung", "Tulang belakang melengkung", "Gerak & sendi"],
];

export type ConditionSeed = {
  slug: string;
  name: string;
  system: string;
  severity: "ringan" | "sedang" | "berat";
  description: string;
  advice: string;
  redFlags: string;
  symptoms: string[];
  structures: string[];
};

export const CONDITION_SEED: ConditionSeed[] = [
  {
    slug: "infark-miokard",
    name: "Serangan jantung (infark miokard)",
    system: "Kardiovaskular",
    severity: "berat",
    description:
      "Aliran darah ke sebagian otot jantung tersumbat, biasanya oleh bekuan pada arteri koroner, sehingga jaringan jantung mulai rusak.",
    advice: "Segera hubungi layanan darurat. Hentikan aktivitas dan jangan mengemudi sendiri ke rumah sakit.",
    redFlags: "Nyeri dada menekan > 15 menit, menjalar ke lengan/rahang, disertai keringat dingin atau sesak.",
    symptoms: ["nyeri-dada", "sesak-napas", "keringat-dingin", "mual", "nyeri-lengan-kiri", "nyeri-rahang", "pusing"],
    structures: ["left-ventricle", "heart", "aorta", "left-coronary-artery", "anterior-interventricular-artery", "right-coronary-artery", "circumflex-artery"],
  },
  {
    slug: "angina-pektoris",
    name: "Angina pektoris",
    system: "Kardiovaskular",
    severity: "sedang",
    description:
      "Nyeri dada akibat otot jantung kekurangan oksigen sementara, sering muncul saat aktivitas dan mereda saat istirahat.",
    advice: "Periksakan ke dokter untuk evaluasi jantung (EKG, uji treadmill). Hindari pemicu aktivitas berat sebelum diperiksa.",
    redFlags: "Nyeri muncul saat istirahat, makin sering, atau tidak mereda dalam 15 menit.",
    symptoms: ["nyeri-dada", "sesak-napas", "kelelahan", "nyeri-lengan-kiri"],
    structures: ["left-ventricle", "heart", "left-coronary-artery", "anterior-interventricular-artery", "right-coronary-artery"],
  },
  {
    slug: "gagal-jantung",
    name: "Gagal jantung",
    system: "Kardiovaskular",
    severity: "berat",
    description:
      "Jantung tidak mampu memompa darah secukupnya, menyebabkan cairan menumpuk di paru dan tungkai.",
    advice: "Perlu penanganan dokter secara berkala. Batasi garam, pantau berat badan harian dan bengkak.",
    redFlags: "Sesak berat saat berbaring, batuk berbusa merah muda, kenaikan berat badan cepat.",
    symptoms: ["sesak-napas", "kelelahan", "bengkak-kaki", "batuk", "berdebar"],
    structures: ["heart", "lung"],
  },
  {
    slug: "hipertensi",
    name: "Hipertensi",
    system: "Kardiovaskular",
    severity: "sedang",
    description:
      "Tekanan darah menetap tinggi sehingga memaksa jantung bekerja lebih keras dan merusak pembuluh darah dalam jangka panjang. Sering tanpa gejala.",
    advice: "Ukur tekanan darah rutin, kurangi garam, aktif bergerak, dan konsultasi bila hasil berulang di atas 140/90.",
    redFlags: "Sakit kepala hebat dengan penglihatan kabur, nyeri dada, atau lemah satu sisi.",
    symptoms: ["sakit-kepala", "pusing", "penglihatan-kabur", "berdebar"],
    structures: ["aorta", "left-ventricle", "kidney"],
  },
  {
    slug: "fibrilasi-atrium",
    name: "Fibrilasi atrium",
    system: "Kardiovaskular",
    severity: "sedang",
    description:
      "Irama serambi jantung tidak teratur dan cepat, meningkatkan risiko bekuan darah dan stroke.",
    advice: "Perlu rekam EKG dan evaluasi dokter. Jangan abaikan jantung berdebar yang berulang.",
    redFlags: "Berdebar disertai pingsan, nyeri dada, atau tanda stroke.",
    symptoms: ["berdebar", "pusing", "sesak-napas", "kelelahan", "pingsan"],
    structures: ["left-atrium", "right-atrium", "heart"],
  },
  {
    slug: "dvt",
    name: "Trombosis vena dalam (DVT)",
    system: "Kardiovaskular",
    severity: "berat",
    description:
      "Bekuan darah terbentuk pada vena dalam tungkai. Bekuan dapat lepas dan menyumbat paru (emboli paru).",
    advice: "Segera periksa ke fasilitas kesehatan bila satu tungkai tiba-tiba bengkak dan nyeri.",
    redFlags: "Sesak napas mendadak atau nyeri dada tajam pada orang dengan tungkai bengkak.",
    symptoms: ["bengkak-kaki", "nyeri-betis", "kemerahan-sendi"],
    structures: ["femoral-vein", "iliac-artery", "tibial-artery"],
  },
  {
    slug: "pneumonia",
    name: "Pneumonia",
    system: "Pernapasan",
    severity: "sedang",
    description:
      "Infeksi pada jaringan paru (alveoli) yang terisi cairan atau nanah, disebabkan bakteri, virus, atau jamur.",
    advice: "Periksa ke dokter; foto toraks mungkin diperlukan. Istirahat, cairan cukup, dan antibiotik bila disebabkan bakteri.",
    redFlags: "Sesak berat, bibir kebiruan, kebingungan, atau demam tinggi tak turun pada lansia/anak.",
    symptoms: ["demam", "batuk", "sesak-napas", "nyeri-dada", "menggigil", "kelelahan", "dahak"],
    structures: ["lung", "bronchus"],
  },
  {
    slug: "asma",
    name: "Asma",
    system: "Pernapasan",
    severity: "sedang",
    description:
      "Peradangan kronis saluran napas yang membuatnya menyempit dan hipersensitif sehingga muncul serangan mengi dan sesak.",
    advice: "Kenali pemicu, gunakan obat pelega dan pengontrol sesuai anjuran dokter.",
    redFlags: "Sulit berbicara satu kalimat penuh, obat pelega tidak membantu, bibir membiru.",
    symptoms: ["sesak-napas", "mengi", "batuk", "nyeri-dada"],
    structures: ["bronchus", "trachea", "lung"],
  },
  {
    slug: "ppok",
    name: "Penyakit paru obstruktif kronik (PPOK)",
    system: "Pernapasan",
    severity: "sedang",
    description:
      "Kerusakan progresif paru dan saluran napas, terutama akibat rokok, yang membatasi aliran udara keluar.",
    advice: "Berhenti merokok adalah langkah terpenting. Spirometri dan terapi inhalasi dari dokter.",
    redFlags: "Sesak memburuk mendadak, dahak berubah warna dan banyak, demam.",
    symptoms: ["batuk-kronis", "sesak-napas", "mengi", "dahak", "kelelahan"],
    structures: ["lung", "bronchus"],
  },
  {
    slug: "tuberkulosis",
    name: "Tuberkulosis paru",
    system: "Pernapasan",
    severity: "berat",
    description:
      "Infeksi Mycobacterium tuberculosis pada paru yang menular lewat percikan dahak. Pengobatan minimal 6 bulan dan harus tuntas.",
    advice: "Periksa dahak (TCM) dan foto toraks. Pengobatan gratis tersedia di puskesmas. Gunakan masker, ventilasi baik.",
    redFlags: "Batuk berdarah banyak, sesak berat, berat badan turun drastis.",
    symptoms: ["batuk-kronis", "batuk-darah", "demam", "keringat-malam", "penurunan-berat-badan", "kelelahan", "hilang-nafsu-makan"],
    structures: ["lobe-superior", "lung"],
  },
  {
    slug: "emboli-paru",
    name: "Emboli paru",
    system: "Pernapasan",
    severity: "berat",
    description:
      "Penyumbatan arteri paru, umumnya oleh bekuan yang berasal dari vena tungkai.",
    advice: "Kondisi darurat; segera ke IGD.",
    redFlags: "Sesak mendadak, nyeri dada tajam saat menarik napas, batuk darah, pingsan.",
    symptoms: ["sesak-napas", "nyeri-dada", "batuk-darah", "berdebar", "bengkak-kaki"],
    structures: ["pulmonary-trunk", "lung", "femoral-vein"],
  },
  {
    slug: "faringitis",
    name: "Faringitis / radang tenggorokan",
    system: "Pernapasan",
    severity: "ringan",
    description:
      "Peradangan tenggorokan, paling sering karena virus. Sebagian kecil karena bakteri Streptococcus.",
    advice: "Istirahat, minum hangat, kumur air garam. Periksa bila demam tinggi atau berlangsung > 5 hari.",
    redFlags: "Sulit bernapas, air liur menetes, tidak mampu menelan cairan.",
    symptoms: ["nyeri-tenggorokan", "demam", "sulit-menelan", "batuk"],
    structures: ["larynx", "trachea"],
  },
  {
    slug: "gangguan-tiroid-hipo",
    name: "Hipotiroidisme",
    system: "Endokrin",
    severity: "sedang",
    description:
      "Kelenjar tiroid kurang menghasilkan hormon sehingga metabolisme tubuh melambat.",
    advice: "Pemeriksaan TSH dan fT4; terapi pengganti hormon bila terbukti.",
    redFlags: "Sangat mengantuk, suhu tubuh rendah, kebingungan.",
    symptoms: ["kelelahan", "kenaikan-berat-badan", "kulit-kering", "intoleransi-dingin", "konstipasi"],
    structures: ["thyroid"],
  },
  {
    slug: "gangguan-tiroid-hiper",
    name: "Hipertiroidisme",
    system: "Endokrin",
    severity: "sedang",
    description:
      "Produksi hormon tiroid berlebih mempercepat metabolisme dan denyut jantung.",
    advice: "Pemeriksaan TSH dan fT4; konsultasi endokrinologi.",
    redFlags: "Demam, denyut sangat cepat, gelisah ekstrem (krisis tiroid).",
    symptoms: ["berdebar", "penurunan-berat-badan", "tremor", "keringat-berlebih", "kelelahan"],
    structures: ["thyroid", "heart"],
  },
  {
    slug: "gerd",
    name: "Refluks asam lambung (GERD)",
    system: "Pencernaan",
    severity: "ringan",
    description:
      "Asam lambung naik ke kerongkongan karena katup bawah esofagus melemah, menimbulkan rasa terbakar di dada.",
    advice: "Makan porsi kecil, hindari berbaring setelah makan, kurangi kopi, pedas, dan lemak. Periksa bila berlangsung > 2 minggu.",
    redFlags: "Sulit menelan progresif, muntah darah, tinja hitam, berat badan turun.",
    symptoms: ["nyeri-ulu-hati", "regurgitasi", "nyeri-dada", "batuk", "sulit-menelan"],
    structures: ["esophagus", "stomach"],
  },
  {
    slug: "gastritis",
    name: "Gastritis / tukak lambung",
    system: "Pencernaan",
    severity: "ringan",
    description:
      "Peradangan atau luka pada dinding lambung, sering terkait infeksi H. pylori, obat antinyeri, atau alkohol.",
    advice: "Hindari pemicu (obat antinyeri, alkohol, makanan pedas). Periksa H. pylori bila berulang.",
    redFlags: "Muntah darah atau seperti ampas kopi, tinja hitam pekat.",
    symptoms: ["nyeri-ulu-hati", "mual", "kembung", "muntah", "hilang-nafsu-makan"],
    structures: ["stomach", "duodenum"],
  },
  {
    slug: "apendisitis",
    name: "Apendisitis",
    system: "Pencernaan",
    severity: "berat",
    description:
      "Peradangan usus buntu. Nyeri biasanya dimulai di sekitar pusar lalu berpindah ke perut kanan bawah.",
    advice: "Segera periksa; sering memerlukan operasi. Jangan makan atau minum obat pencahar.",
    redFlags: "Nyeri hebat menyebar, perut keras, demam tinggi (kemungkinan pecah).",
    symptoms: ["nyeri-perut-kanan-bawah", "demam", "mual", "muntah", "hilang-nafsu-makan"],
    structures: ["appendix", "cecum"],
  },
  {
    slug: "hepatitis",
    name: "Hepatitis",
    system: "Pencernaan",
    severity: "sedang",
    description:
      "Peradangan hati, paling sering oleh virus hepatitis A, B, atau C, juga akibat alkohol atau obat.",
    advice: "Pemeriksaan fungsi hati dan penanda virus. Vaksinasi tersedia untuk hepatitis A dan B.",
    redFlags: "Kebingungan, perdarahan, perut membesar, kuning makin pekat.",
    symptoms: ["kulit-kuning", "mual", "kelelahan", "nyeri-perut-kanan-atas", "urine-gelap", "demam", "hilang-nafsu-makan"],
    structures: ["liver"],
  },
  {
    slug: "batu-empedu",
    name: "Batu empedu / kolesistitis",
    system: "Pencernaan",
    severity: "sedang",
    description:
      "Endapan di kantong empedu dapat menyumbat saluran sehingga memicu nyeri dan peradangan, terutama setelah makan berlemak.",
    advice: "USG abdomen. Hindari makanan berlemak tinggi; tindakan operasi sering menjadi solusi.",
    redFlags: "Demam dengan menggigil, kuning, nyeri menetap > 6 jam.",
    symptoms: ["nyeri-perut-kanan-atas", "mual", "muntah", "demam", "kulit-kuning"],
    structures: ["gallbladder", "liver", "bile-duct"],
  },
  {
    slug: "pankreatitis",
    name: "Pankreatitis akut",
    system: "Pencernaan",
    severity: "berat",
    description:
      "Peradangan pankreas, paling sering karena batu empedu atau alkohol; enzim pankreas mencerna jaringannya sendiri.",
    advice: "Perlu dirawat; puasa sementara dan cairan infus.",
    redFlags: "Nyeri sangat hebat, muntah terus-menerus, sesak, tekanan darah turun.",
    symptoms: ["nyeri-perut-atas-punggung", "mual", "muntah", "demam", "kembung"],
    structures: ["pancreas", "gallbladder", "pancreatic-duct", "bile-duct"],
  },
  {
    slug: "gastroenteritis",
    name: "Gastroenteritis (diare akut)",
    system: "Pencernaan",
    severity: "ringan",
    description:
      "Infeksi saluran cerna oleh virus, bakteri, atau parasit yang menyebabkan diare dan muntah.",
    advice: "Ganti cairan dengan oralit, lanjutkan makan ringan. Periksa bila ada darah atau > 3 hari.",
    redFlags: "Tanda dehidrasi berat: sangat haus, tidak kencing, mata cekung, lemas.",
    symptoms: ["diare", "mual", "muntah", "demam", "nyeri-perut", "lemas"],
    structures: ["small-intestine", "jejunum", "ileum", "stomach"],
  },
  {
    slug: "ibs",
    name: "Sindrom iritasi usus besar (IBS)",
    system: "Pencernaan",
    severity: "ringan",
    description:
      "Gangguan fungsi usus kronis tanpa kerusakan struktural: nyeri perut dengan perubahan pola buang air besar.",
    advice: "Catat pemicu makanan, kelola stres, serat cukup. Periksa bila ada gejala alarm.",
    redFlags: "Darah pada tinja, berat badan turun, demam, nyeri membangunkan dari tidur.",
    symptoms: ["nyeri-perut", "kembung", "diare", "konstipasi"],
    structures: ["transverse-colon", "descending-colon", "sigmoid-colon"],
  },
  {
    slug: "divertikulitis",
    name: "Divertikulitis",
    system: "Pencernaan",
    severity: "sedang",
    description:
      "Peradangan kantong kecil pada dinding usus besar, paling sering di sisi kiri bawah (kolon sigmoid).",
    advice: "Periksa dokter; kasus ringan diberi diet dan antibiotik, kasus berat perlu rawat inap.",
    redFlags: "Nyeri hebat, demam tinggi, perut kaku.",
    symptoms: ["nyeri-perut-kiri-bawah", "demam", "konstipasi", "mual"],
    structures: ["sigmoid-colon", "descending-colon"],
  },
  {
    slug: "hemoroid",
    name: "Hemoroid (wasir)",
    system: "Pencernaan",
    severity: "ringan",
    description:
      "Pembengkakan bantalan pembuluh darah di dubur akibat mengejan atau tekanan berulang.",
    advice: "Serat dan cairan cukup, hindari mengejan. Periksa bila perdarahan berulang untuk menyingkirkan penyebab lain.",
    redFlags: "Perdarahan banyak, perubahan pola BAB berkepanjangan, nyeri hebat.",
    symptoms: ["darah-pada-tinja", "nyeri-anus", "konstipasi"],
    structures: ["rectum"],
  },
  {
    slug: "batu-ginjal",
    name: "Batu ginjal / ureter",
    system: "Ginjal & kemih",
    severity: "sedang",
    description:
      "Kristal mineral mengendap di ginjal lalu bergerak ke ureter, memicu nyeri kolik yang sangat kuat.",
    advice: "Minum air 2–3 liter/hari. Periksa USG/CT; batu kecil sering keluar sendiri dengan pereda nyeri.",
    redFlags: "Demam dengan nyeri pinggang, tidak bisa berkemih, muntah terus.",
    symptoms: ["nyeri-kolik-pinggang", "darah-pada-urine", "mual", "muntah", "sering-berkemih", "nyeri-saat-berkemih"],
    structures: ["kidney", "ureter"],
  },
  {
    slug: "isk",
    name: "Infeksi saluran kemih (sistitis)",
    system: "Ginjal & kemih",
    severity: "ringan",
    description:
      "Infeksi kandung kemih, umumnya oleh bakteri E. coli, lebih sering pada perempuan.",
    advice: "Banyak minum, periksa urine; antibiotik sesuai resep.",
    redFlags: "Demam menggigil dan nyeri pinggang (infeksi sudah naik ke ginjal).",
    symptoms: ["nyeri-saat-berkemih", "sering-berkemih", "urine-keruh", "demam", "darah-pada-urine"],
    structures: ["bladder", "ureter"],
  },
  {
    slug: "pielonefritis",
    name: "Pielonefritis",
    system: "Ginjal & kemih",
    severity: "sedang",
    description:
      "Infeksi ginjal akibat naiknya bakteri dari saluran kemih bawah.",
    advice: "Perlu antibiotik dan kadang rawat inap; segera periksa.",
    redFlags: "Demam tinggi menggigil, muntah, tekanan darah rendah.",
    symptoms: ["demam", "nyeri-pinggang", "menggigil", "mual", "nyeri-saat-berkemih"],
    structures: ["kidney", "ureter"],
  },
  {
    slug: "penyakit-ginjal-kronis",
    name: "Penyakit ginjal kronis",
    system: "Ginjal & kemih",
    severity: "berat",
    description:
      "Penurunan fungsi ginjal bertahap, paling sering akibat diabetes dan hipertensi.",
    advice: "Kontrol gula darah dan tekanan darah; periksa kreatinin dan protein urine.",
    redFlags: "Sesak berat, urine hampir tidak ada, kebingungan.",
    symptoms: ["kelelahan", "bengkak-kaki", "mual", "gatal", "urine-berkurang", "sesak-napas"],
    structures: ["kidney", "adrenal-gland"],
  },
  {
    slug: "stroke",
    name: "Stroke",
    system: "Saraf",
    severity: "berat",
    description:
      "Aliran darah ke bagian otak terputus (iskemik) atau pembuluh pecah (hemoragik). Setiap menit berharga.",
    advice: "Hubungi layanan darurat segera; catat waktu gejala pertama muncul. Ingat FAST: wajah, lengan, bicara, waktu.",
    redFlags: "Wajah miring, lemah satu sisi, bicara pelo, sakit kepala hebat mendadak.",
    symptoms: ["kelemahan-satu-sisi", "bicara-pelo", "wajah-miring", "pusing", "sakit-kepala-hebat", "penglihatan-kabur", "kebingungan"],
    structures: ["brain", "carotid-artery"],
  },
  {
    slug: "migrain",
    name: "Migrain",
    system: "Saraf",
    severity: "ringan",
    description:
      "Sakit kepala berdenyut berulang, sering sebelah, kerap disertai mual dan sensitif cahaya atau suara; dapat didahului aura.",
    advice: "Istirahat di ruang gelap, catat pemicu, obat sesuai anjuran dokter.",
    redFlags: "Sakit kepala terburuk seumur hidup, demam dengan leher kaku, kelemahan atau gangguan bicara.",
    symptoms: ["sakit-kepala", "mual", "sensitif-cahaya", "penglihatan-kabur", "muntah"],
    structures: ["cerebrum", "cranium"],
  },
  {
    slug: "meningitis",
    name: "Meningitis",
    system: "Saraf",
    severity: "berat",
    description:
      "Peradangan selaput pelindung otak dan sumsum tulang belakang, bisa karena virus atau bakteri.",
    advice: "Darurat medis. Segera ke IGD.",
    redFlags: "Demam, leher kaku, sakit kepala hebat, ruam yang tidak memudar, penurunan kesadaran.",
    symptoms: ["demam", "sakit-kepala-hebat", "kaku-leher", "sensitif-cahaya", "mual", "kebingungan"],
    structures: ["brain", "spinal-cord"],
  },
  {
    slug: "epilepsi",
    name: "Epilepsi",
    system: "Saraf",
    severity: "sedang",
    description:
      "Kecenderungan otak mengalami lepasan listrik abnormal berulang yang tampak sebagai kejang.",
    advice: "Evaluasi neurologi (EEG, pencitraan). Jaga tubuh tetap aman saat kejang, jangan masukkan benda ke mulut.",
    redFlags: "Kejang > 5 menit, kejang beruntun, sulit bernapas setelah kejang.",
    symptoms: ["kejang", "kebingungan", "pingsan"],
    structures: ["cerebrum"],
  },
  {
    slug: "parkinson",
    name: "Penyakit Parkinson",
    system: "Saraf",
    severity: "sedang",
    description:
      "Degenerasi sel penghasil dopamin di batang otak/ganglia basal, menimbulkan tremor istirahat, kekakuan, dan gerakan melambat.",
    advice: "Konsultasi neurolog; fisioterapi dan obat dopaminergik memperbaiki kualitas hidup.",
    redFlags: "Sering jatuh, sulit menelan, halusinasi.",
    symptoms: ["tremor", "kaku-otot", "gerakan-lambat"],
    structures: ["brainstem", "cerebrum"],
  },
  {
    slug: "hnp",
    name: "Hernia nukleus pulposus (HNP) lumbal",
    system: "Muskuloskeletal",
    severity: "sedang",
    description:
      "Inti bantalan antar-ruas (diskus) menonjol dan menekan akar saraf, paling sering pada L4–L5 dan L5–S1, memicu nyeri ke tungkai (ischialgia).",
    advice: "Sebagian besar membaik dengan istirahat relatif, fisioterapi, dan obat. MRI bila gejala menetap.",
    redFlags: "Sulit menahan BAB/BAK, baal di selangkangan, kelemahan tungkai progresif.",
    symptoms: ["nyeri-punggung-bawah", "nyeri-menjalar-tungkai", "kesemutan", "kelemahan-tungkai"],
    structures: ["disc-L4-L5", "disc-L5-S1", "sciatic-nerve", "vertebra-L4", "vertebra-L5"],
  },
  {
    slug: "skoliosis",
    name: "Skoliosis",
    system: "Muskuloskeletal",
    severity: "ringan",
    description:
      "Lengkung tulang belakang ke samping lebih dari 10°, sering muncul pada masa pertumbuhan remaja.",
    advice: "Pemeriksaan rontgen dan pemantauan sudut Cobb; tindakan bergantung pada derajat lengkung.",
    redFlags: "Lengkung bertambah cepat, nyeri hebat, gangguan saraf.",
    symptoms: ["tulang-belakang-melengkung", "nyeri-punggung-bawah"],
    structures: ["spine"],
  },
  {
    slug: "osteoartritis-lutut",
    name: "Osteoartritis lutut",
    system: "Muskuloskeletal",
    severity: "sedang",
    description:
      "Kerusakan tulang rawan sendi lutut yang berkembang bertahap karena usia, berat badan, atau cedera lama.",
    advice: "Turunkan berat badan, latihan penguat otot paha, kompres hangat/dingin, obat sesuai anjuran.",
    redFlags: "Lutut tiba-tiba bengkak panas dengan demam, tidak bisa menumpu.",
    symptoms: ["nyeri-sendi", "kaku-sendi", "bengkak-sendi", "krepitus"],
    structures: ["patella", "femur", "tibia"],
  },
  {
    slug: "osteoporosis",
    name: "Osteoporosis",
    system: "Muskuloskeletal",
    severity: "sedang",
    description:
      "Kepadatan tulang menurun sehingga mudah patah, terutama ruas tulang belakang, pergelangan, dan pangkal paha.",
    advice: "Asupan kalsium dan vitamin D, latihan beban, pemeriksaan densitas tulang (DXA) pada usia risiko.",
    redFlags: "Nyeri punggung mendadak setelah gerakan ringan, tidak mampu berdiri setelah jatuh.",
    symptoms: ["penurunan-tinggi-badan", "nyeri-punggung-bawah", "patah-tulang", "tulang-belakang-melengkung"],
    structures: ["spine", "femur", "radius"],
  },
  {
    slug: "artritis-reumatoid",
    name: "Artritis reumatoid",
    system: "Muskuloskeletal",
    severity: "sedang",
    description:
      "Penyakit autoimun yang menyerang selaput sendi, khas simetris pada sendi jari tangan dan pergelangan.",
    advice: "Diagnosis dini penting; konsultasi reumatolog untuk obat pengendali penyakit.",
    redFlags: "Sendi sangat panas dan bengkak mendadak, demam, sesak napas.",
    symptoms: ["nyeri-sendi", "kaku-sendi-pagi", "bengkak-sendi", "kelelahan", "demam"],
    structures: ["metacarpals", "phalanges-hand", "carpals"],
  },
  {
    slug: "gout",
    name: "Gout (asam urat)",
    system: "Muskuloskeletal",
    severity: "ringan",
    description:
      "Kristal asam urat menumpuk di sendi, paling sering ibu jari kaki, menimbulkan serangan nyeri mendadak.",
    advice: "Kompres dingin, istirahatkan sendi, hindari jeroan dan alkohol, periksa kadar asam urat.",
    redFlags: "Demam, sendi sangat panas dan tidak membaik dalam beberapa hari.",
    symptoms: ["nyeri-jempol-kaki", "bengkak-sendi", "kemerahan-sendi", "nyeri-sendi"],
    structures: ["metatarsals", "phalanges-foot"],
  },
  {
    slug: "carpal-tunnel",
    name: "Sindrom terowongan karpal",
    system: "Muskuloskeletal",
    severity: "ringan",
    description:
      "Saraf median tertekan di pergelangan tangan, menyebabkan kesemutan ibu jari hingga jari manis, terutama malam hari.",
    advice: "Bidai pergelangan malam hari, ubah ergonomi kerja; EMG bila menetap.",
    redFlags: "Otot pangkal ibu jari mengecil, baal terus-menerus.",
    symptoms: ["kesemutan", "nyeri-pergelangan-tangan", "kelemahan-genggaman"],
    structures: ["median-nerve", "carpals"],
  },
  {
    slug: "tendinitis-achilles",
    name: "Tendinitis Achilles",
    system: "Muskuloskeletal",
    severity: "ringan",
    description:
      "Peradangan tendon di belakang tumit akibat beban berlebih, umum pada pelari.",
    advice: "Kurangi beban, latihan peregangan dan eksentrik betis, alas kaki yang sesuai.",
    redFlags: "Bunyi 'pop' mendadak dan tidak bisa berjinjit (kemungkinan robek).",
    symptoms: ["nyeri-tumit", "nyeri-otot", "bengkak-sendi"],
    structures: ["achilles-tendon", "gastrocnemius", "calcaneus"],
  },
  {
    slug: "cedera-hamstring",
    name: "Cedera otot hamstring",
    system: "Muskuloskeletal",
    severity: "ringan",
    description:
      "Robekan sebagian serat otot paha belakang, sering saat sprint atau peregangan mendadak.",
    advice: "RICE awal, peregangan dan penguatan bertahap sebelum kembali berolahraga.",
    redFlags: "Memar luas, tidak bisa berjalan, benjolan di paha.",
    symptoms: ["nyeri-otot", "bengkak-kaki"],
    structures: ["biceps-femoris", "semitendinosus"],
  },
  {
    slug: "tmd",
    name: "Gangguan sendi temporomandibular",
    system: "Muskuloskeletal",
    severity: "ringan",
    description:
      "Gangguan sendi rahang dan otot pengunyah, sering terkait bruksisme atau stres.",
    advice: "Diet lunak sementara, kompres hangat, hindari mengunyah permen karet; konsultasi dokter gigi.",
    redFlags: "Rahang terkunci, tidak bisa menutup mulut.",
    symptoms: ["nyeri-rahang", "bunyi-klik-rahang", "sulit-membuka-mulut", "sakit-kepala"],
    structures: ["mandible", "masseter", "temporalis"],
  },
  {
    slug: "anemia",
    name: "Anemia",
    system: "Darah",
    severity: "sedang",
    description:
      "Jumlah sel darah merah atau hemoglobin rendah sehingga pengantaran oksigen menurun; sering akibat kekurangan zat besi.",
    advice: "Periksa darah lengkap dan feritin, cari penyebab (haid, gizi, perdarahan saluran cerna).",
    redFlags: "Sesak saat istirahat, nyeri dada, pingsan, tinja hitam.",
    symptoms: ["kelelahan", "pucat", "pusing", "berdebar", "sesak-napas"],
    structures: ["heart", "spleen"],
  },
  {
    slug: "diabetes",
    name: "Diabetes melitus",
    system: "Endokrin",
    severity: "sedang",
    description:
      "Gula darah tinggi menahun karena kekurangan atau resistensi insulin produksi pankreas.",
    advice: "Periksa gula darah puasa dan HbA1c; atur makan, aktivitas fisik, obat sesuai dokter.",
    redFlags: "Napas berbau buah, muntah, kebingungan (ketoasidosis).",
    symptoms: ["sering-haus", "sering-berkemih", "kelelahan", "penurunan-berat-badan", "penglihatan-kabur"],
    structures: ["pancreas", "kidney"],
  },
  {
    slug: "dbd",
    name: "Demam berdarah dengue (DBD)",
    system: "Infeksi",
    severity: "berat",
    description:
      "Infeksi virus dengue lewat nyamuk Aedes. Fase kritis terjadi hari ke-3 sampai ke-6 saat demam turun, ditandai kebocoran plasma.",
    advice: "Perbanyak cairan, periksa trombosit dan hematokrit berkala. Jangan konsumsi aspirin/ibuprofen.",
    redFlags: "Nyeri perut hebat, muntah terus, perdarahan, tangan kaki dingin, lemas saat demam turun.",
    symptoms: ["demam-tinggi", "sakit-kepala", "nyeri-belakang-mata", "nyeri-otot", "ruam", "mual", "perdarahan-ringan"],
    structures: ["liver", "spleen"],
  },
  {
    slug: "tifoid",
    name: "Demam tifoid",
    system: "Infeksi",
    severity: "sedang",
    description:
      "Infeksi Salmonella typhi dari makanan atau air tercemar yang terutama menyerang usus halus bagian akhir (ileum).",
    advice: "Periksa ke dokter; antibiotik dan istirahat. Cuci tangan dan konsumsi air matang.",
    redFlags: "Nyeri perut hebat, tinja berdarah, penurunan kesadaran.",
    symptoms: ["demam", "nyeri-perut", "sakit-kepala", "hilang-nafsu-makan", "diare", "konstipasi"],
    structures: ["ileum", "spleen"],
  },
];
